### ISSUE TITLE
Get rid of unnecessary allocations

### ISSUE THREAD

**Issue by DmiAS** [waclawthedev/go-sugaring#1]
Hi! I just noticed in you code at line 99 and 107 you perform append operations without previous array allocation. I guess you can allocate slice before loop, because you know the length of map.
https://github.com/waclawthedev/go-sugaring/blob/60730179bfd9d6e7aadd49e2cac211709e1883f6/sugar.go#L99

**Comment by waclawthedev** [comment]
@DmiAS thanks. I applied the changes: [https://github.com/waclawthedev/go-sugaring/releases/tag/v1.0.1](https://github.com/waclawthedev/go-sugaring/releases/tag/v1.0.1)
